package com.mult.dao;

import com.mult.model.SuccessKilled;
import com.mult.model.SuccessKilledExample;
import com.mult.model.SuccessKilledKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuccessKilledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int countByExample(SuccessKilledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int deleteByExample(SuccessKilledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int insert(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int insertSelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    List<SuccessKilled> selectByExample(SuccessKilledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    SuccessKilled selectByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SuccessKilled record, @Param("example") SuccessKilledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SuccessKilled record, @Param("example") SuccessKilledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SuccessKilled record);
}