package com.mult.dao;

import com.mult.model.SuccessKilled;
import com.mult.model.SuccessKilledKey;

public interface SuccessKilledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int insert(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int insertSelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    SuccessKilled selectByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SuccessKilled record);
}